services:
  # service kafka:
  kafka:
    image: confluentinc/cp-kafka:7.8.3
    container_name: kafka
    ports:
      - "${KAFKA_LOOPBACK_PORT}:${KAFKA_LOOPBACK_PORT}"
    environment:
      KAFKA_KRAFT_MODE: 'true'
      CLUSTER_ID: 1L6g7nGhU-eAKfL--X25wo
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:${KAFKA_LOOPBACK_PORT},PLAINTEXT_INTERNAL://:${KAFKA_INTERNAL_PORT},CONTROLLER://:${KAFKA_CONTROLLER_PORT}
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${KAFKA_LOOPBACK_HOST}:${KAFKA_LOOPBACK_PORT},PLAINTEXT_INTERNAL://${KAFKA_INTERNAL_HOST}:${KAFKA_INTERNAL_PORT}
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:${KAFKA_CONTROLLER_PORT}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_HEAP_OPTS: -Xmx512M -Xms512M
    volumes:
    - kafka_data:/var/lib/kafka/data
    networks:
    - dependency-network
    healthcheck:
    # this healthcheck could be improved
      test:
        - CMD
        - nc
        - -z
        - localhost
        - '9092'
      interval: 5s
      timeout: 5s
      retries: 10

  # service kafka-ui:
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: ${KAFKA_INTERNAL_HOST}:${KAFKA_INTERNAL_PORT}
    ports:
      - "8081:8080"
    networks:
      - dependency-network

  # service scheduler:
  scheduler:
    build:
      context: .
      dockerfile: services/scheduler/Dockerfile
    container_name: scheduler
    ports:
      - "${SCHEDULER_PORT}:${SCHEDULER_PORT}"
    env_file:
      - .env
    networks:
      - dependency-network
    depends_on:
      kafka:
        condition: service_healthy

  # service gateway:
  gateway:
    build:
      context: .
      dockerfile: services/gateway/Dockerfile
    container_name: gateway
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    env_file:
      - .env
    networks:
      - dependency-network
    depends_on:
      scheduler:
        condition: service_started

  # service repository-storage-service:
  repository-storage-service:
    build:
      context: .
      dockerfile: services/repository_storage_service/Dockerfile
    container_name: repository-storage-service
    ports:
      - "${REPOSITORY_STORAGE_SERVICE_PORT}:${REPOSITORY_STORAGE_SERVICE_PORT}"
    env_file:
      - .env
      - services/repository_storage_service/.env
    networks:
      - dependency-network
    depends_on:
      kafka:
        condition: service_healthy

  # service repository-scanner-service:
  repository-scanner-service:
    build:
      context: .
      dockerfile: services/repository_scanner_service/Dockerfile
    container_name: repository-scanner-service
    ports:
      - "${REPOSITORY_SCANNER_SERVICE_PORT}:${REPOSITORY_SCANNER_SERVICE_PORT}"
    env_file:
      - .env
    networks:
      - dependency-network
    depends_on:
      kafka:
        condition: service_healthy

  # service llm-service:
  llm-service:
    build:
      context: .
      dockerfile: services/llm_service/Dockerfile
    container_name: llm-service
    ports:
      - "${LLM_SERVICE_PORT}:${LLM_SERVICE_PORT}"
    env_file:
      - .env
      - services/llm_service/.env
    networks:
      - dependency-network
    extra_hosts:
      - "${LOCAL_OLLAMA_DOCKER_HOST}:host-gateway"
    depends_on:
      mcp-server:
        condition: service_started
      kafka:
        condition: service_healthy

  # service registry-service:
  registry-service:
    build:
      context: .
      dockerfile: services/registry_service/Dockerfile
    container_name: registry-service
    ports:
      - "${REGISTRY_SERVICE_PORT}:${REGISTRY_SERVICE_PORT}"
    env_file:
      - .env
      - services/registry_service/.env
    networks:
      - dependency-network
    depends_on:
      kafka:
        condition: service_healthy

  # service mcp-server:
  mcp-server:
    build:
      context: .
      dockerfile: services/mcp_server/Dockerfile
    container_name: mcp-server
    ports:
      - "${MCP_SERVER_PORT}:${MCP_SERVER_PORT}"
    env_file:
      - .env
    networks:
      - dependency-network
    depends_on:
      kafka:
        condition: service_healthy

  # service security-intelligence-service:
  security-intelligence-service:
    build:
      context: .
      dockerfile: services/security_intelligence_service/Dockerfile
    container_name: security-intelligence-service
    ports:
      - "${SECURITY_INTELLIGENCE_SERVICE_PORT}:${SECURITY_INTELLIGENCE_SERVICE_PORT}"
    env_file:
      - .env
    networks:
      - dependency-network
    depends_on:
      llm-service:
        condition: service_started
      kafka:
        condition: service_healthy

volumes:
  kafka_data: null

networks:
  dependency-network:
    driver: bridge
