[project]
name = "repository-storage-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "common",
    "events",
    "fastapi>=0.139.2",
    "gitpython>=3.1.52",
    "pygithub>=2.9.1",
    "uvicorn>=0.51.0",
    "python-dotenv>=1.2.2",
]

[tool.uv.sources]
common = { workspace = true }
events = { workspace = true }

[project.scripts]
repository-storage-service = "repository_storage_service.__main__:main"
